services:
  backend:

    ports:
      - 8000:8000
      - 5678:5678
    command: 
      [
        "sh",
        "-c",
        "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
      ]

    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

