services:
  backend:
    depends_on:
      - app-postgresDB
    image: investmentstrackerapp_backend
    container_name: investmentstrackerapp_backend
    environment:
      POSTGRES_DB_NAME:  ${POSTGRES_DB_NAME-postgres}
      POSTGRES_DB_USER:  ${POSTGRES_DB_USER-postgres}
      POSTGRES_DB_PASSWORD:  ${POSTGRES_DB_PASSWORD-postgres}
      POSTGRES_DB_HOST:  ${POSTGRES_DB_HOST-app-postgresDB}
      POSTGRES_DB_PORT:  ${POSTGRES_DB_PORT-5432}
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  frontend:
    image: investmentstrackerapp-frontend
    container_name: investmentstrackerapp_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  app-postgresDB:
      image: postgres
      container_name: investmentstrackerapp-postgresDB
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${POSTGRES_DB_USER-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD-postgres}
        POSTGRES_DB: ${POSTGRES_DB_NAME-postgres}
        PGPORT: ${POSTGRES_DB_PORT-5432}

volumes:
  postgres_data: