# Generated by Django 5.0.3 on 2024-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketasset',
            name='is_tradable',
        ),
        migrations.AlterField(
            model_name='exchangemarket',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='exchangemarket',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
