# Generated by Django 5.0.3 on 2024-03-27 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_account_asset_deposit_transaction_withdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='co_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_owned_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='PLN', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='commission_currency',
            field=models.CharField(default='PLN', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='PLN', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_currency',
            field=models.CharField(default='PLN', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='PLN', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='co_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_owned_wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
