# Generated by Django 5.0.3 on 2024-04-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_assettypeassociation_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketasset',
            name='is_etf',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='marketasset',
            name='is_share',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='marketetf',
            name='marketasset_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='marketetf', serialize=False, to='wallets.marketasset'),
        ),
        migrations.AlterField(
            model_name='marketshare',
            name='marketasset_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='marketshare', serialize=False, to='wallets.marketasset'),
        ),
    ]
