# Generated by Django 5.0.3 on 2024-04-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_marketasset_is_etf_marketasset_is_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketetf',
            name='marketasset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.marketasset'),
        ),
        migrations.AlterField(
            model_name='marketshare',
            name='marketasset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.marketasset'),
        ),
    ]
