# Generated by Django 5.0.3 on 2024-04-04 09:30

import wallets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_remove_account_co_owner_remove_account_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=100, validators=[wallets.models.validate_name_length]),
        ),
    ]
