# Generated by Django 5.0.3 on 2024-04-04 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_alter_wallet_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('owner', 'name')},
        ),
    ]
