# Generated by Django 5.0.3 on 2024-04-18 08:44

import django.core.validators
import django.db.models.deletion
import wallets.models.asset
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_assetprice_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallets.wallet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetprice',
            name='date',
            field=models.DateField(validators=[wallets.models.asset.past_or_present_date]),
        ),
        migrations.AlterField(
            model_name='assetprice',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallets.currency'),
        ),
    ]
