# Generated by Django 5.0.3 on 2024-04-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_alter_wallet_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='co_owner',
            new_name='co_owners',
        ),
    ]
