# Generated by Django 5.0.3 on 2024-04-22 09:58

import django.core.validators
import wallets.models.deposit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_deposit_wallet_alter_assetprice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposited_at',
            field=models.DateTimeField(validators=[wallets.models.deposit.past_or_present_time]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
