# Generated by Django 5.0.3 on 2024-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_rename_bought_at_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('S', 'Sell'), ('B', 'Buy')], max_length=1),
        ),
    ]
