# Generated by Django 5.0.3 on 2024-04-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_rename_co_owner_account_co_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
