# Generated by Django 5.0.3 on 2024-04-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_alter_account_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='wallet',
            new_name='wallets',
        ),
    ]
