# Generated by Django 5.0.3 on 2024-04-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0015_alter_userasset_sell_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userasset',
            unique_together=set(),
        ),
    ]
