# Generated by Django 5.0.3 on 2024-04-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_account_current_balance_alter_deposit_amount_and_more'),
        ('wallets', '0016_alter_userasset_unique_together'),
    ]

    operations = [
    ]
