# Generated by Django 5.0.3 on 2024-04-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0018_rename_short_name_country_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
