# Generated by Django 5.0.3 on 2024-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0019_rename_full_name_currency_name_currency_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='account',
            name='wallets',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='wallets.wallet'),
        ),
    ]
