# Generated by Django 5.0.3 on 2024-05-01 08:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0024_alter_treasurybonds_issuer_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryBondsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('S', 'Sell'), ('B', 'Buy')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_currency_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_bonds_transactions', to='wallets.account')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_bonds_transactions', to='wallets.treasurybonds')),
                ('commission_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_bonds_transactions_commission', to='wallets.currency')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_bonds_transactions', to='wallets.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_bonds_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_bonds_transactions', to='wallets.wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='BondsTransaction',
        ),
    ]
