# Generated by Django 5.0.3 on 2024-05-01 08:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0025_treasurybondstransaction_delete_bondstransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurybondstransaction',
            name='currency_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='treasurybondstransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='wallets.account'),
        ),
        migrations.AlterField(
            model_name='treasurybondstransaction',
            name='commission_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_commission', to='wallets.currency'),
        ),
        migrations.AlterField(
            model_name='treasurybondstransaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='wallets.currency'),
        ),
        migrations.AlterField(
            model_name='treasurybondstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treasurybondstransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='wallets.wallet'),
        ),
        migrations.CreateModel(
            name='MarketAssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('S', 'Sell'), ('B', 'Buy')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_currency_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_asset_transactions', to='wallets.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.marketasset')),
                ('commission_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_commission', to='wallets.currency')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='wallets.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_asset_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_asset_transactions', to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userasset',
            name='buy_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_user_assets', to='wallets.marketassettransaction'),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='sell_transaction',
            field=models.ManyToManyField(blank=True, related_name='sell_user_assets', to='wallets.marketassettransaction'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
