# Generated by Django 5.0.3 on 2024-05-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0027_alter_marketassettransaction_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurybondstransaction',
            name='bond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.treasurybonds'),
        ),
    ]
