# Generated by Django 5.0.3 on 2024-05-01 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0028_alter_treasurybondstransaction_bond'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasurybonds',
            options={'verbose_name': 'Treasury Bonds', 'verbose_name_plural': 'Treasury Bonds'},
        ),
        migrations.AddField(
            model_name='userasset',
            name='commission_currency_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
