# Generated by Django 5.0.3 on 2024-05-02 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0032_usertreasurybonds_active_alter_retailbonds_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailbonds',
            name='duration',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailbonds',
            name='duration_unit',
            field=models.CharField(choices=[('D', 'Days'), ('M', 'Months'), ('Y', 'Years')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
