# Generated by Django 5.0.3 on 2024-05-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0036_rename_currency_marketassettransaction_account_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userasset',
            old_name='currency',
            new_name='account_currency',
        ),
    ]
