# Generated by Django 5.0.3 on 2024-05-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0038_remove_account_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailbonds',
            name='is_intrest_rate_fixed',
            field=models.BooleanField(default=True),
        ),
    ]
