# Generated by Django 5.0.3 on 2024-05-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0039_retailbonds_is_intrest_rate_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailbonds',
            name='current_value',
        ),
    ]
