# Generated by Django 5.0.3 on 2024-04-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_remove_marketasset_is_tradable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettypeassociation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.marketasset'),
        ),
    ]
