# Generated by Django 5.0.3 on 2024-04-17 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_marketetf_marketasset_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
