# Generated by Django 5.0.3 on 2024-04-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_userasset_active_userasset_buy_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_asset',
        ),
    ]
