# Generated by Django 5.0.3 on 2024-04-22 14:15

import django.core.validators
import django.db.models.deletion
import wallets.models.withdrawal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0017_merge_20240422_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallets.currency'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawn_at',
            field=models.DateTimeField(validators=[wallets.models.withdrawal.past_or_present_time]),
        ),
    ]
