# Generated by Django 5.0.3 on 2024-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0018_withdrawal_wallet_alter_withdrawal_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='country',
        ),
        migrations.AddField(
            model_name='currency',
            name='countries',
            field=models.ManyToManyField(related_name='currencies', to='wallets.country'),
        ),
    ]
