# Generated by Django 5.0.3 on 2024-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0019_remove_currency_country_currency_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.AddField(
            model_name='account',
            name='currencies',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='wallets.currency'),
        ),
    ]
