# Generated by Django 5.0.3 on 2024-04-30 21:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0022_remove_account_current_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailBonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('issuer', models.CharField(max_length=100)),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('initial_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('premature_withdrawal_fee', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.assettype')),
                ('price_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.currency')),
            ],
        ),
        migrations.CreateModel(
            name='UserRetailBonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('issue_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='wallets.account')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='wallets.retailbonds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'User Bonds',
                'verbose_name_plural': 'User Bonds',
            },
        ),
        migrations.CreateModel(
            name='TreasuryBonds',
            fields=[
                ('retailbonds_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.retailbonds')),
                ('issuer_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.country')),
            ],
            options={
                'verbose_name': 'Government Bonds',
                'verbose_name_plural': 'Government Bonds',
            },
            bases=('wallets.retailbonds',),
        ),
        migrations.CreateModel(
            name='BondsTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.transaction')),
                ('bond_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.treasurybonds')),
            ],
            bases=('wallets.transaction',),
        ),
    ]
