# Generated by Django 5.0.3 on 2024-04-30 21:53

import django.db.models.deletion
import wallets.models.asset
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0023_retailbonds_userretailbonds_treasurybonds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurybonds',
            name='issuer_country',
            field=models.ForeignKey(limit_choices_to=wallets.models.asset.TreasuryBonds.limit_to_bond_countries, on_delete=django.db.models.deletion.PROTECT, to='wallets.country'),
        ),
    ]
