# Generated by Django 5.0.3 on 2024-05-01 08:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0026_treasurybondstransaction_currency_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketassettransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='wallets.account'),
        ),
        migrations.AlterField(
            model_name='marketassettransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketassettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='wallets.wallet'),
        ),
        migrations.CreateModel(
            name='UserTreasuryBonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('issue_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='wallets.account')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='wallets.retailbonds')),
                ('buy_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_user_assets', to='wallets.treasurybondstransaction')),
                ('sell_transaction', models.ManyToManyField(blank=True, related_name='sell_user_assets', to='wallets.treasurybondstransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'User Bonds',
                'verbose_name_plural': 'User Bonds',
            },
        ),
        migrations.DeleteModel(
            name='UserRetailBonds',
        ),
    ]
