# Generated by Django 5.0.3 on 2024-05-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0029_alter_treasurybonds_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userasset',
            old_name='sell_transaction',
            new_name='sell_transactions',
        ),
        migrations.RenameField(
            model_name='usertreasurybonds',
            old_name='sell_transaction',
            new_name='sell_transactions',
        ),
    ]
