# Generated by Django 5.0.3 on 2024-05-12 16:44

import django.core.validators
import django.db.models.deletion
import wallets.models.transaction
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0033_retailbonds_duration_retailbonds_duration_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketassettransaction',
            name='transaction_date',
            field=models.DateTimeField(validators=[wallets.models.transaction.past_or_present_time]),
        ),
        migrations.AlterField(
            model_name='retailbonds',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='retailbonds',
            name='initial_interest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='retailbonds',
            name='premature_withdrawal_fee',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='treasurybondstransaction',
            name='transaction_date',
            field=models.DateTimeField(validators=[wallets.models.transaction.past_or_present_time]),
        ),
        migrations.AlterField(
            model_name='usertreasurybonds',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.CreateModel(
            name='CurrencyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='wallets.currency')),
            ],
            options={
                'verbose_name_plural': 'Currency Prices',
            },
        ),
    ]
