# Generated by Django 5.0.3 on 2024-05-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0034_alter_marketassettransaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketassettransaction',
            name='commission_currency',
        ),
        migrations.RemoveField(
            model_name='marketassettransaction',
            name='commission_currency_price',
        ),
        migrations.RemoveField(
            model_name='treasurybondstransaction',
            name='commission_currency',
        ),
        migrations.RemoveField(
            model_name='treasurybondstransaction',
            name='commission_currency_price',
        ),
        migrations.RemoveField(
            model_name='userasset',
            name='commission_currency',
        ),
        migrations.RemoveField(
            model_name='userasset',
            name='commission_currency_price',
        ),
    ]
