# Generated by Django 5.0.3 on 2024-05-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0035_remove_marketassettransaction_commission_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketassettransaction',
            old_name='currency',
            new_name='account_currency',
        ),
        migrations.RenameField(
            model_name='treasurybondstransaction',
            old_name='currency',
            new_name='account_currency',
        ),
    ]
