# Generated by Django 5.0.3 on 2024-05-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0037_rename_currency_userasset_account_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='current_value',
        ),
    ]
